import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import "../../scss/beschrijving.scss";
import { faHeart } from '@fortawesome/free-regular-svg-icons'

function Beschrijving(){
    return(
        <div className="descriptionCont">
            <FontAwesomeIcon icon={faHeart} className="heartIcon" size="4x"/>
            <div className="mainInfo">
                <h3 className="titleProjectD">Lincoln</h3>
                <h4 className="authorProjectD">Henk De Steen</h4>
            </div>
            <div className="sideInfo">
                <p className="descriptionProject">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tristique et egestas quis ipsum suspendisse ultrices. Etiam dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Malesuada proin libero nunc consequat interdum varius sit amet mattis. Blandit turpis cursus in hac. In nulla posuere sollicitudin aliquam. Odio aenean sed adipiscing diam donec adipiscing tristique risus. In vitae turpis massa sed elementum. In nibh mauris cursus mattis molestie. At risus viverra adipiscing at. Luctus accumsan tortor posuere ac ut consequat semper viverra. Velit ut tortor pretium viverra suspendisse potenti. Varius morbi enim nunc faucibus a pellentesque sit amet porttitor. Non enim praesent elementum facilisis leo vel fringilla est ullamcorper. Donec ac odio tempor orci dapibus. Congue quisque egestas diam in arcu cursus euismod.

Elementum facilisis leo vel fringilla est ullamcorper. Velit egestas dui id ornare. Non enim praesent elementum facilisis leo vel fringilla est ullamcorper. Elit pellentesque habitant morbi tristique senectus et. Semper risus in hendrerit gravida rutrum. Integer malesuada nunc vel risus commodo viverra. Ut sem nulla pharetra diam. Hac habitasse platea dictumst vestibulum rhoncus. Diam donec adipiscing tristique risus nec feugiat in. Sit amet consectetur adipiscing elit. Duis tristique sollicitudin nibh sit. Metus aliquam eleifend mi in.

Vitae turpis massa sed elementum tempus egestas sed sed risus. Tempus egestas sed sed risus pretium quam vulputate dignissim. Aliquam ut porttitor leo a diam sollicitudin tempor. Scelerisque varius morbi enim nunc. Vitae tortor condimentum lacinia quis. Leo in vitae turpis massa sed elementum. Praesent tristique magna sit amet purus gravida quis blandit turpis. Amet commodo nulla facilisi nullam vehicula ipsum a. Enim eu turpis egestas pretium. Id neque aliquam vestibulum morbi blandit cursus risus at.

Cras fermentum odio eu feugiat pretium nibh ipsum. Cras semper auctor neque vitae tempus quam pellentesque. Sollicitudin aliquam ultrices sagittis orci a. Massa id neque aliquam vestibulum morbi. Pellentesque nec nam aliquam sem. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. At erat pellentesque adipiscing commodo elit at imperdiet. Faucibus nisl tincidunt eget nullam non nisi est sit amet. Interdum varius sit amet mattis vulputate enim nulla aliquet. Adipiscing elit duis tristique sollicitudin. Massa eget egestas purus viverra accumsan in nisl. Duis convallis convallis tellus id interdum velit laoreet id. Egestas purus viverra accumsan in nisl nisi scelerisque eu. Enim nec dui nunc mattis enim. Et netus et malesuada fames ac. Interdum posuere lorem ipsum dolor sit amet consectetur. Blandit aliquam etiam erat velit scelerisque in dictum non. Et pharetra pharetra massa massa ultricies mi quis hendrerit. Turpis massa sed elementum tempus egestas sed. Vitae congue eu consequat ac felis donec et odio.

In mollis nunc sed id semper risus in hendrerit gravida. Est pellentesque elit ullamcorper dignissim cras tincidunt. Pellentesque eu tincidunt tortor aliquam nulla. Tempus iaculis urna id volutpat. Vulputate odio ut enim blandit volutpat maecenas volutpat. Sed libero enim sed faucibus turpis in. Venenatis tellus in metus vulputate eu scelerisque felis. Sit amet justo donec enim. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Netus et malesuada fames ac turpis egestas. Elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Risus nec feugiat in fermentum posuere urna. Semper quis lectus nulla at volutpat. Scelerisque in dictum non consectetur a erat nam at lectus. Arcu bibendum at varius vel pharetra vel turpis nunc eget.

Enim sit amet venenatis urna. Odio aenean sed adipiscing diam donec. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Lacinia at quis risus sed vulputate odio. Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Et ligula ullamcorper malesuada proin. Facilisis leo vel fringilla est ullamcorper eget nulla. Commodo sed egestas egestas fringilla phasellus. Egestas maecenas pharetra convallis posuere morbi leo. Proin fermentum leo vel orci porta non pulvinar. Lorem donec massa sapien faucibus et molestie ac. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. At volutpat diam ut venenatis tellus in. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Nibh tellus molestie nunc non blandit massa.

Nunc eget lorem dolor sed viverra ipsum nunc. Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Id faucibus nisl tincidunt eget nullam non. Amet tellus cras adipiscing enim eu turpis egestas pretium aenean. Velit scelerisque in dictum non consectetur a erat. Porttitor lacus luctus accumsan tortor posuere ac ut. Consequat nisl vel pretium lectus quam. Neque gravida in fermentum et sollicitudin ac. Dictum at tempor commodo ullamcorper a lacus. Nunc pulvinar sapien et ligula ullamcorper. Sed risus ultricies tristique nulla. Nisl pretium fusce id velit ut tortor pretium viverra. 
Enim sit amet venenatis urna. Odio aenean sed adipiscing diam donec. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Lacinia at quis risus sed vulputate odio. Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Et ligula ullamcorper malesuada proin. Facilisis leo vel fringilla est ullamcorper eget nulla. Commodo sed egestas egestas fringilla phasellus. Egestas maecenas pharetra convallis posuere morbi leo. Proin fermentum leo vel orci porta non pulvinar. Lorem donec massa sapien faucibus et molestie ac. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. At volutpat diam ut venenatis tellus in. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Nibh tellus molestie nunc non blandit massa.

Nunc eget lorem dolor sed viverra ipsum nunc. Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Volutpat odio facilisis mauris sit amet massa vitae tortor condimentum. Id faucibus nisl tincidunt eget nullam non. Amet tellus cras adipiscing enim eu turpis egestas pretium aenean. Velit scelerisque in dictum non consectetur a erat. Porttitor lacus luctus accumsan tortor posuere ac ut. Consequat nisl vel pretium lectus quam. Neque gravida in fermentum et sollicitudin ac. Dictum at tempor commodo ullamcorper a lacus. Nunc pulvinar sapien et ligula ullamcorper. Sed risus ultricies tristique nulla. Nisl pretium fusce id velit ut tortor pretium viverra.</p>
            </div>

        </div>
    )
}
export default Beschrijving